version: '2'
services:
    sportup-app:
        image: sportup
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://sportup-postgresql:5432/sportup
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    sportup-postgresql:
        extends:
            file: postgresql.yml
            service: sportup-postgresql
